# Generated by Django 4.0.4 on 2023-07-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person_being_wished', models.CharField(max_length=1000)),
                ('mail_of_person_being_wished', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_of_person_doing_wishing', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
                ('wish_message', models.TextField()),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WishMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('video', models.FileField(upload_to='media')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.wish')),
            ],
        ),
    ]
